In [73]:
# Frequency of word occurence is Bag Of words

# limitations of BOW
# i) vocabulary size may be 10000 and that might lead the text representation to be long, consuming lots of memory
# ii) Sparse Representation - will contain lots of 0's in the vector, consumes lots or memory and resources
# iii) doesn't capture meaning of words, as different sentences will have different words which will lead to different kind of 
# text representation(vector)

In [74]:
import pandas as pd
import numpy as np

In [75]:
df = pd.read_csv('C:\DS practice\spam.csv')

In [76]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [77]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

##### def get_spam_number(x):
    if x == 'spam':
        return 1
    else:
        return 0
df['spam'] = df.Category.apply(get_spam_number) 

In [78]:
df['spam'] = df.Category.apply(lambda x : 1 if x == 'spam' else 0)

In [79]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [80]:
X = df.Message
y = df.spam

In [81]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8)

In [82]:
len(X_test)

1115

In [83]:
len(X_train)

4457

In [84]:
type(X_train)

pandas.core.series.Series

In [85]:
X_train[:5]

3820    sorry brah, just finished the last of my exams...
1300    Great to hear you are settling well. So what's...
4765    Hi.:)technical support.providing assistance to...
873                       I'll text you when I drop x off
5567    This is the 2nd time we have tried 2 contact u...
Name: Message, dtype: object

In [87]:
X_train[:5][3820]

'sorry brah, just finished the last of my exams, what up'

In [88]:
X_train.values

array(['sorry brah, just finished the last of my exams, what up',
       "Great to hear you are settling well. So what's happenin wit ola?",
       'Hi.:)technical support.providing assistance to us customer through call and email:)',
       ...,
       "Sorry, I'll call later in meeting any thing related to trade please call Arul. &lt;#&gt;",
       'Me too! Have a lovely night xxx',
       "Yup i'm still having coffee wif my frens... My fren drove she'll give me a lift..."],
      dtype=object)

In [89]:
type(X_train.values)

numpy.ndarray

In [90]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7718 sparse matrix of type '<class 'numpy.int64'>'
	with 58930 stored elements in Compressed Sparse Row format>

In [91]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [92]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [93]:
X_train_cv.shape  #7696 unique words OR unique columns

(4457, 7718)

In [94]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'ú1', '〨ud'], dtype=object)

In [95]:
v.get_feature_names_out()[1000:1050]

array(['anywhere', 'apart', 'apartment', 'apeshit', 'aphex', 'apo',
       'apologetic', 'apologise', 'apologize', 'app', 'apparently',
       'appendix', 'applausestore', 'applebees', 'apples', 'application',
       'apply', 'applyed', 'applying', 'appointment', 'appointments',
       'appreciate', 'appreciated', 'approaches', 'approve', 'approved',
       'approx', 'apps', 'appt', 'appy', 'april', 'aproach', 'apt',
       'aptitude', 'aquarius', 'ar', 'arab', 'arcade', 'archive', 'ard',
       'are', 'area', 'aren', 'arent', 'arestaurant', 'aretaking',
       'areyouunique', 'argentina', 'argh', 'argue'], dtype=object)

In [96]:
v.get_feature_names_out().shape

(7718,)

In [97]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [98]:
v.vocabulary_

{'sorry': 6321,
 'brah': 1475,
 'just': 3862,
 'finished': 2864,
 'the': 6803,
 'last': 4009,
 'of': 4882,
 'my': 4652,
 'exams': 2694,
 'what': 7456,
 'up': 7161,
 'great': 3234,
 'to': 6917,
 'hear': 3372,
 'you': 7686,
 'are': 1040,
 'settling': 6030,
 'well': 7436,
 'so': 6274,
 'happenin': 3320,
 'wit': 7528,
 'ola': 4915,
 'hi': 3419,
 'technical': 6730,
 'support': 6609,
 'providing': 5462,
 'assistance': 1099,
 'us': 7194,
 'customer': 2116,
 'through': 6865,
 'call': 1610,
 'and': 953,
 'email': 2568,
 'll': 4154,
 'text': 6774,
 'when': 7462,
 'drop': 2454,
 'off': 4884,
 'this': 6844,
 'is': 3736,
 '2nd': 401,
 'time': 6890,
 'we': 7395,
 'have': 3351,
 'tried': 7022,
 'contact': 1973,
 'won': 7556,
 '750': 611,
 'pound': 5326,
 'prize': 5414,
 'claim': 1815,
 'easy': 2511,
 '087187272008': 143,
 'now1': 4831,
 'only': 4936,
 '10p': 263,
 'per': 5139,
 'minute': 4492,
 'bt': 1543,
 'national': 4693,
 'rate': 5562,
 'many': 4344,
 'people': 5137,
 'seems': 5982,
 'be': 1271,


In [99]:
v.get_feature_names_out()[1060]

'arng'

In [100]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [105]:
np.where(X_train_np[3820] != 0)

(array([ 399, 1183, 1512, 1524, 2600, 2981, 3200, 3635, 3748, 4057, 4262,
        6835, 7179, 7496], dtype=int64),)

In [102]:
X_train[:4]

3820    sorry brah, just finished the last of my exams...
1300    Great to hear you are settling well. So what's...
4765    Hi.:)technical support.providing assistance to...
873                       I'll text you when I drop x off
Name: Message, dtype: object

In [104]:
X_train[3820]

'sorry brah, just finished the last of my exams, what up'

In [107]:
X_train_np[3820][399]

1

In [111]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [112]:
X_test_cv = v.transform(X_test)

In [114]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       955
           1       0.99      0.93      0.95       160

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [117]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [119]:
from sklearn.pipeline import Pipeline
 
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [121]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [123]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       955
           1       0.99      0.93      0.95       160

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [148]:
#Import necessary libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [149]:
df = pd.read_csv('C:\DS practice\IMDB Dataset.csv')

In [150]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [151]:
df['positive'] = df.sentiment.apply(lambda x: 1 if x == 'positive' else 0)

In [152]:
df.head()

review sentiment  positive
0  One of the other reviewers has mentioned that ...  positive         1
1  A wonderful little production. <br /><br />The...  positive         1
2  I thought this was a wonderful way to spend ti...  positive         1
3  Basically there's a family where a little boy ...  negative         0
4  Petter Mattei's "Love in the Time of Money" is...  positive         1

In [153]:
X = df.review
y = df.positive

In [154]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8)

In [155]:
cv = CountVectorizer()

X_train_cv1 = cv.fit_transform(X_train)

In [146]:
RFC = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('random_forest', (RandomForestClassifier(n_estimators = 50, criterion = 'entropy')))
])

In [157]:
RFC.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('random_forest',
                 RandomForestClassifier(criterion='entropy', n_estimators=50))])

In [159]:
y_pred = RFC.predict(X_test)

In [160]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84      4998
           1       0.84      0.84      0.84      5002

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000

