In [268]:
from sklearn import svm, datasets
iris = datasets.load_iris()
import pandas as pd
import numpy as np

In [269]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)

In [270]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [271]:
df['flower'] = iris.target

In [272]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])

In [273]:
X = df.drop('flower', axis = 1)
y = df.flower

In [274]:
from sklearn.model_selection import train_test_split

In [275]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7)

In [276]:
model = svm.SVC(kernel = 'rbf', C = 30, gamma = 'auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9333333333333333

In [277]:
from sklearn.model_selection import cross_val_score

In [278]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 30, gamma = 'auto'), X, y, cv = 6)

array([0.96, 1.  , 0.88, 0.92, 0.96, 1.  ])

In [279]:
cross_val_score(svm.SVC(kernel = 'linear', C = 30, gamma = 'auto'), X, y, cv = 6)

array([1.  , 1.  , 0.92, 0.92, 0.92, 1.  ])

In [280]:
cross_val_score(svm.SVC(kernel = 'poly', C = 30, gamma = 'auto'), X, y, cv = 6)

array([0.96, 1.  , 0.92, 0.96, 0.92, 1.  ])

In [281]:
kernel = ['rbf','linear','poly']     # for loop for getting the best Kernel and C score
C = [10,25,50]
avg_scores={}
for kval in kernel:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel = kval, C = cval, gamma = 'auto'), X ,y, cv = 5)
        avg_scores[kval + '-' + str(cval)] = np.average(cv_scores)
avg_scores

{'rbf-10': 0.9800000000000001,
 'rbf-25': 0.9666666666666668,
 'rbf-50': 0.96,
 'linear-10': 0.9733333333333334,
 'linear-25': 0.96,
 'linear-50': 0.9666666666666666,
 'poly-10': 0.9666666666666666,
 'poly-25': 0.9533333333333334,
 'poly-50': 0.96}

In [282]:
from sklearn.model_selection import GridSearchCV

In [283]:
gsc = GridSearchCV(svm.SVC(gamma='auto'),{
    'kernel' : ['rbf','poly','linear'],
    'C' : [10,25,50]
} , cv = 5, return_train_score = False)

In [284]:
gsc.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 25, 50],
                         'kernel': ['rbf', 'poly', 'linear']})

In [285]:
gsc.cv_results_

{'mean_fit_time': array([0.00180526, 0.00319171, 0.00140886, 0.00140638, 0.00631599,
        0.00121074, 0.00160103, 0.00520144, 0.00099187]),
 'std_fit_time': array([4.04675473e-04, 1.70988298e-03, 5.06313037e-04, 5.00707226e-04,
        6.00595726e-03, 4.04378361e-04, 4.78250754e-04, 3.43006446e-03,
        2.16351691e-05]),
 'mean_score_time': array([0.00139756, 0.00098782, 0.00118127, 0.00102515, 0.00099201,
        0.00097661, 0.00099511, 0.00097847, 0.00100045]),
 'std_score_time': array([8.18120803e-04, 8.57167017e-06, 3.85700034e-04, 4.89243755e-05,
        2.12309837e-05, 3.10535600e-05, 1.73219917e-05, 3.42035530e-05,
        8.29395152e-06]),
 'param_C': masked_array(data=[10, 10, 10, 25, 25, 25, 50, 50, 50],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'poly', 'linear', 'rbf', 'poly', 'linear',
                    'rbf', '

In [286]:
df2 = pd.DataFrame(gsc.cv_results_)
df2

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001805      0.000405         0.001398        0.000818      10   
1       0.003192      0.001710         0.000988        0.000009      10   
2       0.001409      0.000506         0.001181        0.000386      10   
3       0.001406      0.000501         0.001025        0.000049      25   
4       0.006316      0.006006         0.000992        0.000021      25   
5       0.001211      0.000404         0.000977        0.000031      25   
6       0.001601      0.000478         0.000995        0.000017      50   
7       0.005201      0.003430         0.000978        0.000034      50   
8       0.000992      0.000022         0.001000        0.000008      50   

  param_kernel                         params  split0_test_score  \
0          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
1         poly    {'C': 10, 'kernel': 'poly'}           1.000000   
2       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 25, 'kernel': 'rbf'}           0.966667   
4         poly    {'C': 25, 'kernel': 'poly'}           0.966667   
5       linear  {'C': 25, 'kernel': 'linear'}           1.000000   
6          rbf     {'C': 50, 'kernel': 'rbf'}           1.000000   
7         poly    {'C': 50, 'kernel': 'poly'}           0.966667   
8       linear  {'C': 50, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.966667           0.966667                1.0   
1           1.000000           0.900000           0.933333                1.0   
2           1.000000           0.900000           0.966667                1.0   
3           1.000000           0.900000           0.966667                1.0   
4           0.966667           0.900000           0.933333                1.0   
5           1.000000           0.900000           0.900000                1.0   
6           0.966667           0.900000           0.933333                1.0   
7           0.966667           0.933333           0.933333                1.0   
8           1.000000           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.966667        0.042164                4  
2         0.973333        0.038873                2  
3         0.966667        0.036515                3  
4         0.953333        0.033993                9  
5         0.960000        0.048990                6  
6         0.960000        0.038873                6  
7         0.960000        0.024944                6  
8         0.966667        0.042164                4

In [287]:
df2[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10          rbf         0.980000
1      10         poly         0.966667
2      10       linear         0.973333
3      25          rbf         0.966667
4      25         poly         0.953333
5      25       linear         0.960000
6      50          rbf         0.960000
7      50         poly         0.960000
8      50       linear         0.966667

In [288]:
dir(gsc)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [289]:
gsc.best_estimator_

SVC(C=10, gamma='auto')

In [290]:
gsc.best_params_

{'C': 10, 'kernel': 'rbf'}

In [291]:
gsc.best_score_

0.9800000000000001

In [292]:
from sklearn.model_selection import RandomizedSearchCV

In [293]:
rsc = RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'kernel' : ['rbf','poly','linear'],
    'C' : [10,25,50]
} , cv = 5, n_iter = 5, return_train_score = False)

In [294]:
rsc.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [10, 25, 50],
                                        'kernel': ['rbf', 'poly', 'linear']})

In [295]:
rsc.cv_results_

{'mean_fit_time': array([0.00169997, 0.0062438 , 0.00129304, 0.00647988, 0.00099659]),
 'std_fit_time': array([6.22433853e-04, 3.12840933e-03, 3.95676032e-04, 5.63946361e-03,
        1.50789149e-07]),
 'mean_score_time': array([0.00163455, 0.00124183, 0.00104914, 0.00102878, 0.00099659]),
 'std_score_time': array([8.19851288e-04, 3.93004708e-04, 9.68762020e-05, 6.35396920e-05,
        1.50789149e-07]),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'poly', 'rbf'],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[50, 50, 50, 25, 25],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'linear', 'C': 50},
  {'kernel': 'poly', 'C': 50},
  {'kernel': 'rbf', 'C': 50},
  {'kernel': 'poly', 'C': 25},
  {'kernel': 'rbf', 'C': 25}],
 'split0_test_score': array([1.        , 0.96666667, 1.        , 0.96666667, 0.9666

In [296]:
df3 = pd.DataFrame(rsc.cv_results_)
df3

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.001700  6.224339e-04         0.001635    8.198513e-04       linear   
1       0.006244  3.128409e-03         0.001242    3.930047e-04         poly   
2       0.001293  3.956760e-04         0.001049    9.687620e-05          rbf   
3       0.006480  5.639464e-03         0.001029    6.353969e-05         poly   
4       0.000997  1.507891e-07         0.000997    1.507891e-07          rbf   

  param_C                         params  split0_test_score  \
0      50  {'kernel': 'linear', 'C': 50}           1.000000   
1      50    {'kernel': 'poly', 'C': 50}           0.966667   
2      50     {'kernel': 'rbf', 'C': 50}           1.000000   
3      25    {'kernel': 'poly', 'C': 25}           0.966667   
4      25     {'kernel': 'rbf', 'C': 25}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.900000           0.933333                1.0   
1           0.966667           0.933333           0.933333                1.0   
2           0.966667           0.900000           0.933333                1.0   
3           0.966667           0.900000           0.933333                1.0   
4           1.000000           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.966667        0.042164                2  
1         0.960000        0.024944                3  
2         0.960000        0.038873                3  
3         0.953333        0.033993                5  
4         0.966667        0.036515                1

In [297]:
df3[['param_kernel','param_C','mean_test_score']]

param_kernel param_C  mean_test_score
0       linear      50         0.966667
1         poly      50         0.960000
2          rbf      50         0.960000
3         poly      25         0.953333
4          rbf      25         0.966667

In [298]:
rsc.best_estimator_

SVC(C=25, gamma='auto')

In [299]:
rsc.best_score_

0.9666666666666668

In [300]:
rsc.best_params_

{'kernel': 'rbf', 'C': 25}

In [301]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [305]:
model_params = {
    'svm' : {
        'model' : svm.SVC(gamma='auto'),
        'params' : {
            'C' : [10,25,50],
            'kernel' : ['rbf','linear','poly']
        }
    },
    'random_forest' : {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators' : [1,10,20]
        }
    },
    'logistic_regression' : {
        'model' : LogisticRegression(),
        'params' : {
            'C' : [1,5,10]
        }
        
    }
}

In [312]:
scores = []
for model_name,mn in model_params.items():
    gsc = GridSearchCV(mn['model'],mn['params'],cv = 5, return_train_score = False)
    gsc.fit(iris.data,iris.target)
    scores.append({
        'model': model_name,
        'best_score' : gsc.best_score_ ,
        'best_params' : gsc.best_params_
    })

C:\Users\chauzani\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\chauzani\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

In [314]:
df4 = pd.DataFrame(scores)
df4

model  best_score                 best_params
0                  svm    0.980000  {'C': 10, 'kernel': 'rbf'}
1        random_forest    0.966667        {'n_estimators': 20}
2  logistic_regression    0.980000                   {'C': 10}